"""Added foreign keys for Product and Shop models

Revision ID: 455520604182
Revises: 5b703774e3d1
Create Date: 2025-02-25 10:05:55.497302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455520604182'
down_revision = '5b703774e3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shop_id')

    # ### end Alembic commands ###
