"""Updated models after foreign key addition

Revision ID: d4e30e183a29
Revises: 455520604182
Create Date: 2025-02-25 10:35:49.095563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e30e183a29'
down_revision = '455520604182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_product_shop', 'shops', ['shop_id'], ['id'])
        batch_op.drop_column('shop_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_product_shop', type_='foreignkey')
        batch_op.drop_column('shop_id')

    # ### end Alembic commands ###
