"""Renamed backref in Product model to avoid conflict

Revision ID: fdc8fd5c1204
Revises: d4e30e183a29
Create Date: 2025-02-25 10:39:54.914068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc8fd5c1204'
down_revision = 'd4e30e183a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('shop_name')

    # ### end Alembic commands ###
